project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!publications/_template/"
    - "!people/_template/"

website:
  title: "Faraone Lab"
  site-url: "https://faraonelab.github.io"
  repo-url: "https://github.com/faraonelab/faraonelab.github.io.git"
  twitter-card: false
  back-to-top-navigation: true
  page-navigation: false
  search: true
  
  page-footer: 
    background: "#F6F5F3"
    center: |
      © 2026 &middot; Made with {{< fa brands r-project >}} and 
      [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/) by Luis Anholeto
    right:
      - icon: github
        href: https://github.com/faraonelab/faraonelab.github.io.git
  
  navbar:
    search: true
    title: false
    logo: images/faraone-logo.jpg
    background: "#FFF"
    logo-alt: "Faraone Research Group"
    left:
      - href: people/index.qmd
        text: people
      - href: research/index.qmd
      - href: publications/index.qmd
      - href: collaborators-funding/index.qmd
        text: Collaborators and Funding
      - href: news/index.qmd
        text: News
      - href: gallery/index.qmd
        text: Gallery
      - href: courses/index.qmd
        text: Courses
      - href: contact.qmd
        text: Contact

  sidebar:
    - id: empty-to-suppress-sidebars-on-other-pages

format:
  html:
    theme: 
      - styles/custom.scss
      - yeti
    mainfont: Nunito Sans
    toc: true
    link-external-newwindow: true
    date-format: "YYYY-MM-DD" 
    smooth-scroll: true
    resources:
      - images
      - _ejs/publications.ejs
    fig-format: retina
    fig-dpi: 300

execute:
  freeze: auto